export const navigation = [
  ["Projects", "▣", "Проекты"],
  ["Sessions", "◫", "Чат"],
  ["Skills", "✦", "Скиллы"],
  ["MCP", "⌘", "/MCP"],
  ["Accounts", "●", "Аккаунты"],
  ["Models", "⬢", "Модели"],
  ["Tools", "⚒", "Инструменты"],
  ["Memory", "◆", "Память"],
  ["OMP Settings", "⚙", "Настройки OMP"],
  ["App Settings", "⚙", "Настройки приложения"],
] as const;

export const slashCommands = [
  ["/models", "Выбрать и назначить модели"],
  ["/settings", "Настроить поведение OMP"],
  ["/session", "Показать сведения о сессии"],
  ["/mcp list", "Показать серверы /MCP"],
  ["/skills", "Открыть установленные скиллы"],
  ["/usage", "Показать использование провайдера"],
  ["/context", "Проверить окно контекста"],
  ["/compact", "Сжать текущую сессию"],
  ["/login", "Войти в аккаунт провайдера"],
  ["/tools", "Показать инструменты"],
  ["/memory", "Проверить память агента"],
  ["/changelog full", "Открыть историю изменений"],
] as const;

export const settingsTabs = [
  ["Appearance", "◫", "Интерфейс"],
  ["Model", "◕", "Модель и reasoning"],
  ["Interaction", "⌨", "Управление"],
  ["Context", "◒", "Контекст"],
  ["Memory", "◆", "Память"],
  ["Files", "▤", "Файлы"],
  ["Shell", ">_", "Терминал"],
  ["Tools", "⚒", "Инструменты"],
  ["Tasks", "✓", "Задачи"],
  ["Providers", "◎", "Провайдеры"],
  ["Plugins", "⌘", "/MCP и скиллы"],
] as const;

export interface SettingRow {
  section?: string;
  label?: string;
  value?: string;
  description?: string;
}

export const settingsRows: Record<string, SettingRow[]> = {
  Appearance: [
    { section: "Theme" },
    { label: "Dark Theme", value: "titanium", description: "Theme used when the terminal has a dark background" },
    { label: "Light Theme", value: "dark-taiga", description: "Theme used when the terminal has a light background" },
    { label: "Symbol Preset", value: "unicode", description: "Glyph family used throughout selectors and status lines" },
    { label: "Color-Blind Mode", value: "false", description: "Use redundant symbols in addition to semantic color" },
    { section: "Status Line" },
    { label: "Status Line Preset", value: "default", description: "Preset controlling visible footer segments" },
    { label: "Status Line Separator", value: "powerline-thin", description: "Separator between status line segments" },
    { label: "Session Accent", value: "true", description: "Use a per-session accent after the first agent turn" },
    { label: "Transparent Status Line", value: "false", description: "Keep the Dark Titanium status fill" },
    { label: "Compact Thinking Level", value: "false", description: "Show both thinking glyph and label" },
  ],
  Model: [
    { section: "Thinking" },
    { label: "Thinking Level", value: "auto", description: "Reasoning depth for thinking-capable models" },
    { label: "Hide Thinking Blocks", value: "false", description: "Hide model reasoning blocks from the transcript" },
    { label: "Prose Only Thinking", value: "true", description: "Render readable thinking prose only" },
    { label: "Omit Thinking summaries", value: "false", description: "Keep summaries produced by the model" },
    { label: "Loop Guard", value: "true", description: "Detect repeated reasoning loops" },
    { label: "Loop Guard Scan Prose", value: "true", description: "Scan prose for repeated reasoning" },
    { label: "Loop Guard Tool-Call Reminder", value: "true", description: "Remind the model to use tools" },
    { label: "Tool-Call Loop Guard", value: "true", description: "Detect repeated tool calls" },
    { label: "Auto Thinking Model", value: "online", description: "Use online routing for automatic effort" },
    { label: "Auto Thinking Ceiling", value: "xhigh", description: "Maximum automatic thinking level" },
    { section: "Sampling" },
    { label: "Temperature", value: "-1", description: "Use the provider default" },
    { label: "Top P", value: "-1", description: "Use the provider default" },
  ],
  Interaction: [
    { section: "Input" },
    { label: "Steering Mode", value: "one-at-a-time", description: "How to process queued messages while the agent is working" },
    { label: "Follow-Up Mode", value: "one-at-a-time", description: "How follow-up messages are queued" },
    { label: "Interrupt Mode", value: "immediate", description: "When an interrupt takes effect" },
    { label: "Loop Mode", value: "prompt", description: "Prompt before restarting a loop" },
    { label: "Double-Escape Action", value: "tree", description: "Open the session tree on double Escape" },
    { label: "Session Tree Filter", value: "default", description: "Default session tree filter" },
    { label: "Autocomplete Items", value: "5", description: "Maximum slash autocomplete rows" },
    { label: "Emoji Autocomplete", value: "true", description: "Offer emoji completions" },
    { label: "Large Paste Menu", value: "100", description: "Line threshold for the large paste menu" },
    { section: "Approvals" },
    { label: "Tool Approval Policies", value: "{}", description: "Per-tool approval policy overrides" },
    { label: "Tool Approval", value: "yolo", description: "Default tool approval mode" },
  ],
  Context: [
    { section: "General" },
    { label: "Auto-Promote Context", value: "false", description: "Promote to a larger-context model on overflow instead of compacting" },
    { label: "Branch Summaries", value: "false", description: "Summarize session branches" },
    { section: "Compaction" },
    { label: "Auto-Compact", value: "true", description: "Compact automatically near the model limit" },
    { label: "Mid-Turn Compaction", value: "true", description: "Allow safe compaction during long turns" },
    { label: "Compaction Strategy", value: "snapcompact", description: "Current compaction implementation" },
    { label: "Compaction Threshold", value: "default", description: "Use OMP default threshold" },
    { label: "Compaction Token Limit", value: "default", description: "Use OMP default token limit" },
    { label: "Save Handoff Docs", value: "false", description: "Save handoff documents after compaction" },
    { label: "Remote Compaction", value: "true", description: "Allow provider-backed compaction" },
    { label: "Remote Compaction V2", value: "true", description: "Use remote compaction v2" },
    { label: "Idle Compaction", value: "false", description: "Compact while the agent is idle" },
    { label: "Idle Compaction Threshold", value: "200000", description: "Idle compaction token threshold" },
  ],
  Memory: [
    { section: "General" },
    { label: "Memory Backend", value: "off", description: "Off, local summary pipeline, Mnemopi SQLite, or Hindsight remote memory" },
    { section: "Auto-Learn" },
    { label: "Auto-Learn (experimental)", value: "false", description: "Learn reusable facts from completed sessions" },
  ],
  Files: [
    { section: "Editing" },
    { label: "Edit Mode", value: "hashline", description: "Select the edit tool variant (replace, patch, hashline, or apply_patch)" },
    { label: "Fuzzy Match", value: "true", description: "Allow fuzzy edit matching" },
    { label: "Fuzzy Match Threshold", value: "0.95", description: "Minimum fuzzy confidence" },
    { label: "Abort on Failed Preview", value: "false", description: "Abort when a patch preview fails" },
    { label: "Block Auto-Generated Files", value: "true", description: "Protect generated outputs" },
    { label: "Enforce Seen-Line Guard", value: "false", description: "Only edit lines already read" },
    { section: "Reading" },
    { label: "Line Numbers", value: "false", description: "Include line numbers in read output" },
    { label: "Default Read Limit", value: "300", description: "Default maximum read lines" },
    { label: "Markdown Previews", value: "false", description: "Show rendered markdown previews" },
    { label: "Inline Read Previews", value: "false", description: "Show inline read previews" },
    { label: "Read Summaries", value: "true", description: "Summarize long reads" },
  ],
  Shell: [
    { section: "Bash" },
    { label: "Bash", value: "true", description: "Enable the bash tool for shell command execution" },
    { label: "Bash Auto-Background", value: "false", description: "Move slow commands to the background" },
    { label: "Bash Interceptor", value: "false", description: "Intercept shell commands" },
    { label: "direnv Auto-Load", value: "auto", description: "Load direnv automatically" },
    { label: "Shell Minimizer", value: "true", description: "Reduce verbose shell output" },
    { label: "Shell Minimizer Source Outline", value: "default", description: "Outline retained by shell minimizer" },
    { section: "Eval & Runtimes" },
    { label: "Python Eval Backend", value: "true", description: "Enable persistent Python evaluation" },
    { label: "JavaScript Eval Backend", value: "true", description: "Enable JavaScript evaluation" },
    { label: "Ruby Eval Backend", value: "false", description: "Enable Ruby evaluation" },
    { label: "Julia Eval Backend", value: "false", description: "Enable Julia evaluation" },
    { label: "Python Kernel Mode", value: "session", description: "Keep one kernel per session" },
  ],
  Tools: [
    { section: "Available Tools" },
    ...["Todos", "Glob", "Grep", "AST Edit", "Debug", "Launch", "Read URLs"].map((label) => ({ label, value: "true", description: `Enable the ${label.toLowerCase()} tool` })),
    ...["AST Grep", "Speech Generation", "Generate Image", "Computer", "Checkpoint/Rewind"].map((label) => ({ label, value: "false", description: `Enable the ${label.toLowerCase()} tool` })),
    { label: "Inspect Image", value: "auto", description: "Enable when a supported backend is available" },
  ],
  Tasks: [
    { section: "Modes" },
    { label: "Plan Mode", value: "true", description: "Enable read-only planning before execution" },
    { label: "Start in Plan Mode", value: "false", description: "Begin every session in plan mode" },
    { label: "Goal Mode", value: "true", description: "Enable persistent goal tracking" },
    { label: "Goal Status in Footer", value: "true", description: "Show goal status in the footer" },
    { label: "Refresh Title on Replan", value: "true", description: "Refresh the task title after replanning" },
    { section: "Subagents" },
    { label: "Prefer Task Delegation", value: "default", description: "Use default delegation behavior" },
    { label: "Batch Task Calls", value: "true", description: "Launch independent task calls together" },
    { label: "Per-Task Effort", value: "false", description: "Select effort for each task" },
    { label: "Max Concurrent Tasks", value: "32", description: "Upper bound for concurrent tasks" },
    { label: "LSP in Subagents", value: "false", description: "Enable LSP tools in subagents" },
    { label: "Max Task Recursion", value: "2", description: "Maximum delegation depth" },
    { label: "Max Subagent Runtime", value: "0", description: "Maximum subagent runtime" },
  ],
  Providers: [
    { section: "Services" },
    { label: "Max In-Flight Requests", value: "Unlimited", description: "Maximum concurrent LLM requests per provider id" },
    { label: "Web Search Provider Order", value: "default", description: "Preferred web search backend order" },
    { label: "Excluded Web Search Providers", value: "none", description: "Providers excluded from search" },
    { label: "Web Search Timeout", value: "60", description: "Search timeout in seconds" },
    { label: "Gemini web_search model", value: "", description: "Model used for Gemini web search" },
    { label: "Antigravity Endpoint Mode", value: "auto", description: "Automatic endpoint selection" },
    { label: "Image Provider Order", value: "default", description: "Preferred image backend order" },
    { label: "Live Voice", value: "sol", description: "Model used for live voice" },
    { label: "Text-to-Speech Provider", value: "auto", description: "Automatic speech backend selection" },
    { label: "Local TTS Model", value: "kokoro", description: "Local speech model" },
    { label: "Local TTS Voice", value: "af_heart", description: "Local speech voice" },
    { label: "Speech Vocalization", value: "false", description: "Read assistant responses aloud" },
    { label: "Speech Vocalization Mode", value: "assistant", description: "Speech vocalization source" },
  ],
  Plugins: [],
};

export const providerRows = [
  ["ChatGPT Plus/Pro (Codex Subscription)", "вход выполнен", "login"],
  ["Anthropic (Claude Pro/Max)", "", ""],
  ["Z.AI (GLM Coding Plan)", "", ""],
  ["Kimi Code", "", ""],
  ["OpenRouter", "", ""],
  ["GitHub Copilot", "", ""],
  ["Cursor (Claude, GPT, etc.)", "", ""],
  ["Devin", "", ""],
  ["Antigravity (Gemini, Claude, GPT-OSS)", "вход выполнен", "login"],
] as const;

export const modelRows = [
  ["a6api", "gpt-5.6-sol", "1.1m ◫", "бесплатно"],
  ["openai-codex", "gpt-5.6-luna", "272k ◫", "$0.2/1.2"],
  ["a6api", "claude-fable-5", "1m ◫", "бесплатно"],
  ["google-antigravity", "gemini-3.1-pro", "1m ◫", "$2/12"],
  ["google-antigravity", "claude-opus-4-6", "250k ◫", "$5/25"],
  ["openai-codex", "gpt-5.6-sol", "272k ◫", "$5/30"],
  ["a6api", "DeepSeek-V4-Flash", "1m ◫", "бесплатно"],
  ["a6api", "qwen3.6-27b", "262k ◫", "бесплатно"],
] as const;
